FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json, wildcard used so both package.json AND package-lock.json are copied
# slash '/' at the end of app is important, so it created an app directory, otherwise you'll get an error
COPY package.json ./
COPY package-lock.json ./
# Copy app files from src directory
COPY prisma ./prisma

# Install application dependencies
RUN npm install
RUN npx prisma generate
# RUN npx prisma migrate dev
# Copy the rest of your application code to the working directory
COPY . .

# Expose the port your application will run on
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "start:dev"]
